/**
 * User Manual PDF Generation
 * Generates comprehensive user manual PDF for NexaLMS
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Extend jsPDF with lastAutoTable
declare module 'jspdf' {
    interface jsPDF {
        lastAutoTable: { finalY: number };
    }
}

const MANUAL_VERSION = '1.0.0';
const MANUAL_DATE = 'January 7, 2025';

interface ManualOptions {
    schoolName?: string;
    schoolLogo?: string;
}

export async function generateUserManualPdf(_options?: ManualOptions): Promise<jsPDF> {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let currentPage = 1;
    let totalPages = 1;

    // Colors
    const primaryColor: [number, number, number] = [34, 139, 34]; // Green

    // Helper function to add page header
    const addPageHeader = (pageNum: number, chapterTitle?: string) => {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(128, 128, 128);
        doc.text(`NexaLMS User Manual v${MANUAL_VERSION}`, 15, 10);
        
        if (chapterTitle) {
            doc.text(chapterTitle, pageWidth / 2, 10, { align: 'center' });
        }
        
        doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 15, 10, { align: 'right' });
        
        // Line
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.3);
        doc.line(15, 12, pageWidth - 15, 12);
    };

    // Helper function to add page footer
    const addPageFooter = () => {
        doc.setFontSize(7);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(150, 150, 150);
        doc.text(
            `Generated by NexaLMS • © ${new Date().getFullYear()} NexaGen Technologies`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
        doc.text(
            `www.nexagen.co.ke • support@nexagen.co.ke`,
            pageWidth / 2,
            pageHeight - 6,
            { align: 'center' }
        );
    };

    // Helper function to add new page with header/footer
    const addNewPage = (chapterTitle?: string) => {
        doc.addPage();
        currentPage++;
        addPageHeader(currentPage, chapterTitle);
        addPageFooter();
    };

    // Cover Page
    doc.setFillColor(34, 139, 34);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
    
    // White content area
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(15, 20, pageWidth - 30, pageHeight - 40, 5, 5, 'F');
    
    // Logo placeholder
    doc.setFillColor(34, 139, 34);
    doc.circle(pageWidth / 2, 50, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('N', pageWidth / 2, 58, { align: 'center' });
    
    // Title
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.text('NexaLMS', pageWidth / 2, 90, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text('School Management System', pageWidth / 2, 100, { align: 'center' });
    
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('User Manual', pageWidth / 2, 120, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Version ${MANUAL_VERSION}`, pageWidth / 2, 135, { align: 'center' });
    doc.text(MANUAL_DATE, pageWidth / 2, 142, { align: 'center' });
    
    doc.setFontSize(10);
    doc.text('Prepared by', pageWidth / 2, 170, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('NexaGen Technologies', pageWidth / 2, 178, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('www.nexagen.co.ke', pageWidth / 2, 185, { align: 'center' });
    doc.text('support@nexagen.co.ke', pageWidth / 2, 192, { align: 'center' });

    // Table of Contents
    addNewPage('Table of Contents');
    
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Table of Contents', pageWidth / 2, 30, { align: 'center' });
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const tocData = [
        ['Chapter 1', 'Introduction', '3'],
        ['Chapter 2', 'Getting Started', '4'],
        ['Chapter 3', 'School Setup', '5'],
        ['Chapter 4', 'Students', '6'],
        ['Chapter 5', 'Teachers', '7'],
        ['Chapter 6', 'Roles & Permissions', '8'],
        ['Chapter 7', 'Timetable', '9'],
        ['Chapter 8', 'Attendance', '10'],
        ['Chapter 9', 'Examinations', '11'],
        ['Chapter 10', 'Analytics', '12'],
        ['Chapter 11', 'Report Cards', '13'],
        ['Chapter 12', 'Finance', '14'],
        ['Chapter 13', 'Announcements', '15'],
        ['Chapter 14', 'Troubleshooting', '16'],
        ['Chapter 15', 'Frequently Asked Questions', '17'],
        ['Chapter 16', 'Support & Contact', '18'],
    ];
    
    autoTable(doc, {
        startY: 40,
        head: [['Chapter', 'Title', 'Page']],
        body: tocData,
        theme: 'grid',
        headStyles: {
            fillColor: primaryColor,
            textColor: 255,
            fontStyle: 'bold',
            fontSize: 10,
        },
        bodyStyles: {
            fontSize: 9,
            cellPadding: 3,
        },
        alternateRowStyles: {
            fillColor: [245, 255, 245],
        },
        margin: { left: 25, right: 25 },
    });

    // Chapter 1: Introduction
    addNewPage('Chapter 1 - Introduction');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 1', 15, 30);
    doc.setFontSize(20);
    doc.text('Introduction', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const introText = [
        'Welcome to NexaLMS - a comprehensive School Management System designed to streamline',
        'administrative tasks, enhance academic management, and improve communication between',
        'students, teachers, parents, and administrators.',
        '',
        'What is NexaLMS?',
        'NexaLMS is a cloud-based platform that integrates all aspects of school management into',
        'a single, easy-to-use system. From student enrollment to examination management,',
        'fee tracking to attendance monitoring, NexaLMS provides tools to help your school',
        'operate more efficiently.',
        '',
        'Key Features:',
        '• Student and Teacher Management',
        '• Academic Year and Term Configuration',
        '• Examination and Report Card Generation',
        '• Attendance Tracking',
        '• Timetable Management',
        '• Fee Management and Payment Tracking',
        '• Analytics and Reporting',
        '• Communication Tools',
    ];
    
    let yPos = 50;
    introText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 2: Getting Started
    addNewPage('Chapter 2 - Getting Started');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 2', 15, 30);
    doc.setFontSize(20);
    doc.text('Getting Started', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const gettingStartedText = [
        'System Requirements',
        '• Supported browsers: Chrome, Firefox, Safari, Edge (latest versions)',
        '• Minimum internet connection: 5 Mbps for optimal performance',
        '• Recommended screen resolution: 1366x768 or higher',
        '• JavaScript must be enabled in your browser',
        '',
        'Logging In',
        '1. Navigate to your school\'s NexaLMS login page',
        '2. Enter your registered email address',
        '3. Enter your password',
        '4. Click "Sign In" to access the dashboard',
        '',
        'First-Time Setup',
        'Upon first login, you will be guided through the setup wizard:',
        '1. Complete your school profile (name, logo, motto)',
        '2. Configure academic years and terms',
        '3. Set up grade levels and classes',
        '4. Add subjects and departments',
        '5. Import or add students and teachers',
        '',
        'Navigation',
        'The sidebar provides quick access to all major sections:',
        '• Overview - Dashboard and key metrics',
        '• People - Students, teachers, and staff management',
        '• Academics - Classes, subjects, timetable',
        '• Assessment - Examinations, report cards, attendance',
        '• Finance - Fee management and payments',
        '• Administration - Settings, roles, announcements',
    ];
    
    yPos = 50;
    gettingStartedText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 3: School Setup
    addNewPage('Chapter 3 - School Setup');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 3', 15, 30);
    doc.setFontSize(20);
    doc.text('School Setup', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const schoolSetupText = [
        'School Profile',
        'Configure your school\'s basic information that appears on reports and documents.',
        '',
        'Steps:',
        '1. Go to Settings > School Settings',
        '2. Enter school name and motto',
        '3. Upload school logo (recommended: 200x200px PNG)',
        '4. Add contact information and address',
        '5. Set up watermark for official documents',
        '6. Save changes',
        '',
        'Academic Years',
        'Define academic years to organize your school\'s calendar.',
        '',
        'Steps:',
        '1. Navigate to Academics > Academic Years',
        '2. Click "Add Academic Year"',
        '3. Enter year name (e.g., "2024-2025")',
        '4. Set start and end dates',
        '5. Mark as current if active',
        '6. Save',
        '',
        'Terms',
        'Break down academic years into terms for better organization.',
        '',
        'Steps:',
        '1. Go to Academics > Academic Years',
        '2. Select an academic year',
        '3. Click "Add Term"',
        '4. Enter term name and dates',
        '5. Set term number for ordering',
        '6. Save',
        '',
        'Streams and Classes',
        'Organize students into classes and streams based on grade levels.',
        '',
        'Steps:',
        '1. Navigate to Academics > Streams & Classes',
        '2. Create grade levels first (Form 1, Form 2, etc.)',
        '3. Add streams under each grade (East, West, North)',
        '4. Create classes combining grade and stream',
        '5. Assign class teachers to each class',
        '6. Save',
    ];
    
    yPos = 50;
    schoolSetupText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 4: Students
    addNewPage('Chapter 4 - Students');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 4', 15, 30);
    doc.setFontSize(20);
    doc.text('Students', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const studentsText = [
        'Adding a Student',
        'Add individual students with their personal information, academic details, and guardian',
        'information.',
        '',
        'Steps:',
        '1. Go to Students > Add Student',
        '2. Enter personal details (name, date of birth, gender)',
        '3. Add contact information and guardian details',
        '4. Assign class and admission number',
        '5. Upload profile photo (optional)',
        '6. Save the student record',
        '',
        'Bulk Import Students',
        'Import multiple students at once using a CSV template.',
        '',
        'Steps:',
        '1. Go to Students > Import',
        '2. Download the CSV template',
        '3. Fill in student details following the template format',
        '4. Upload the completed CSV file',
        '5. Review and confirm the import',
        '6. Resolve any validation errors',
        '',
        'Editing Student Records',
        'Update student information as needed.',
        '',
        'Steps:',
        '1. Navigate to Students',
        '2. Search for the student',
        '3. Click on the student record',
        '4. Edit the required fields',
        '5. Save changes',
        '',
        'Student Transfer',
        'Handle student transfers within or out of the school.',
        '',
        'Steps:',
        '1. Open the student record',
        '2. Click "Transfer Student"',
        '3. Select transfer type (in/out)',
        '4. Enter transfer details and date',
        '5. Add notes if necessary',
        '6. Confirm the transfer',
    ];
    
    yPos = 50;
    studentsText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 5: Teachers
    addNewPage('Chapter 5 - Teachers');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 5', 15, 30);
    doc.setFontSize(20);
    doc.text('Teachers', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const teachersText = [
        'Adding a Teacher',
        'Create teacher profiles with their qualifications, subjects, and contact information.',
        '',
        'Steps:',
        '1. Go to Staff > Add Teacher',
        '2. Enter personal and professional details',
        '3. Add contact information',
        '4. Specify subjects they can teach',
        '5. Assign TSC number or employee ID',
        '6. Save the teacher record',
        '',
        'Assigning Subjects',
        'Assign subjects to teachers based on their qualifications and expertise.',
        '',
        'Steps:',
        '1. Open teacher profile',
        '2. Go to Subjects section',
        '3. Select subjects from the list',
        '4. Set subject preference levels',
        '5. Save assignments',
        '',
        'Assigning Classes',
        'Assign classes to teachers for subject teaching and class teacher responsibilities.',
        '',
        'Steps:',
        '1. Navigate to Staff',
        '2. Select a teacher',
        '3. Go to Class Assignments',
        '4. Select classes for each subject',
        '5. Set as class teacher if applicable',
        '6. Save assignments',
    ];
    
    yPos = 50;
    teachersText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 6: Roles & Permissions
    addNewPage('Chapter 6 - Roles & Permissions');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 6', 15, 30);
    doc.setFontSize(20);
    doc.text('Roles & Permissions', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const rolesText = [
        'Creating Roles',
        'Create custom roles with specific permissions based on responsibilities.',
        '',
        'Steps:',
        '1. Go to Roles & Permissions',
        '2. Click "Create Role"',
        '3. Enter role name and description',
        '4. Select permissions for each module',
        '5. Save the role',
        '',
        'Assigning Permissions',
        'Configure what each role can view, edit, create, or delete in the system.',
        '',
        'Steps:',
        '1. Edit a role',
        '2. Review each module\'s permissions',
        '3. Check boxes for allowed actions',
        '4. Save changes',
        '5. Assign role to users',
        '',
        'User Management',
        'Create user accounts and assign roles to control system access.',
        '',
        'Steps:',
        '1. Go to Staff or appropriate section',
        '2. Create user account',
        '3. Assign role to the user',
        '4. Set account permissions',
        '5. Send invitation email',
        '6. User sets their password',
    ];
    
    yPos = 50;
    rolesText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 7: Timetable
    addNewPage('Chapter 7 - Timetable');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 7', 15, 30);
    doc.setFontSize(20);
    doc.text('Timetable', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const timetableText = [
        'Configuring Timetable',
        'Set up the timetable structure including periods, days, and break times.',
        '',
        'Steps:',
        '1. Go to Academics > Timetable',
        '2. Configure periods and timing',
        '3. Set school days and breaks',
        '4. Define subject durations',
        '5. Save timetable settings',
        '',
        'Generating Timetable',
        'Automatically generate timetables based on teacher assignments and class schedules.',
        '',
        'Steps:',
        '1. Ensure all teacher assignments are complete',
        '2. Go to Timetable > Generate',
        '3. Select classes and term',
        '4. Click generate timetable',
        '5. Review for conflicts',
        '6. Resolve any conflicts manually',
        '7. Publish the timetable',
        '',
        'Downloading Timetable',
        'Export timetables in various formats for printing and distribution.',
        '',
        'Steps:',
        '1. Open the timetable view',
        '2. Select format (PDF, Excel)',
        '3. Choose scope (class, teacher, school)',
        '4. Click download',
        '5. Print or distribute as needed',
    ];
    
    yPos = 50;
    timetableText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 8: Attendance
    addNewPage('Chapter 8 - Attendance');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 8', 15, 30);
    doc.setFontSize(20);
    doc.text('Attendance', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const attendanceText = [
        'Student Attendance',
        'Record daily student attendance by class.',
        '',
        'Steps:',
        '1. Go to Attendance > Student Attendance',
        '2. Select date and class',
        '3. Mark attendance for each student',
        '4. Add notes for absences if needed',
        '5. Save the attendance record',
        '',
        'Teacher Attendance',
        'Track teacher attendance and punctuality.',
        '',
        'Steps:',
        '1. Navigate to Attendance > Teacher Attendance',
        '2. Select date',
        '3. Mark attendance for each teacher',
        '4. Record leave or absence reasons',
        '5. Save the record',
        '',
        'Attendance Reports',
        'Generate comprehensive attendance reports.',
        '',
        'Steps:',
        '1. Go to Attendance > Reports',
        '2. Select date range and class',
        '3. Choose report type',
        '4. Generate and view report',
        '5. Export if needed',
    ];
    
    yPos = 50;
    attendanceText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 9: Examinations
    addNewPage('Chapter 9 - Examinations');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 9', 15, 30);
    doc.setFontSize(20);
    doc.text('Examinations', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const examsText = [
        'Creating an Examination',
        'Set up examinations for specific terms and classes.',
        '',
        'Steps:',
        '1. Go to Examinations > Create Exam',
        '2. Enter exam name (e.g., "End of Term 1")',
        '3. Select academic year and term',
        '4. Choose participating classes',
        '5. Add subjects with maximum marks',
        '6. Set exam dates if applicable',
        '7. Save and publish the exam',
        '',
        'Uploading Marks',
        'Enter student marks for each subject in an examination.',
        '',
        'Steps:',
        '1. Open the examination',
        '2. Select a subject',
        '3. Enter marks for each student',
        '4. Add remarks if needed',
        '5. Save the marks',
        '6. Repeat for all subjects',
        '',
        'Publishing Results',
        'Make examination results visible to stakeholders.',
        '',
        'Steps:',
        '1. Ensure all subject marks are entered',
        '2. Go to Examinations',
        '3. Select the exam',
        '4. Click "Publish Results"',
        '5. Confirm publication',
        '',
        'Examination Analytics',
        'Analyze examination performance with detailed reports.',
        '',
        'Steps:',
        '1. Open published examination',
        '2. View analytics dashboard',
        '3. Filter by class, subject, or student',
        '4. Export reports as needed',
        '5. Compare with previous exams',
    ];
    
    yPos = 50;
    examsText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 10: Analytics
    addNewPage('Chapter 10 - Analytics');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 10', 15, 30);
    doc.setFontSize(20);
    doc.text('Analytics', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const analyticsText = [
        'Academic Performance',
        'Analyze student and teacher performance with detailed metrics.',
        '',
        'Steps:',
        '1. Go to Analytics > Academic',
        '2. Select examination or time period',
        '3. View mean scores and distributions',
        '4. Compare classes and subjects',
        '5. Identify top and bottom performers',
        '6. Export reports',
        '',
        'Teacher Performance Ranking',
        'Rank teachers based on their students\' performance.',
        '',
        'Steps:',
        '1. Navigate to Analytics > Teachers',
        '2. View ranking by subject',
        '3. Compare class performance',
        '4. Analyze teaching effectiveness',
        '5. Identify professional development needs',
        '',
        'Subject Performance Analysis',
        'Compare performance across subjects.',
        '',
        'Steps:',
        '1. Go to Analytics > Subjects',
        '2. View subject-wise mean scores',
        '3. Compare pass rates',
        '4. Identify difficult subjects',
        '5. Analyze grade distributions',
        '',
        'Trend Analysis',
        'Track performance trends over time.',
        '',
        'Steps:',
        '1. Select time period for analysis',
        '2. View trend graphs',
        '3. Compare terms or years',
        '4. Identify patterns',
        '5. Project future performance',
    ];
    
    yPos = 50;
    analyticsText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 11: Report Cards
    addNewPage('Chapter 11 - Report Cards');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 11', 15, 30);
    doc.setFontSize(20);
    doc.text('Report Cards', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const reportCardsText = [
        'Generating Report Cards',
        'Create report cards for individual students or entire classes.',
        '',
        'Steps:',
        '1. Go to Report Cards > Generate',
        '2. Select examination and class',
        '3. Choose individual student or entire class',
        '4. Toggle fee balance inclusion if needed',
        '5. Preview the report card',
        '6. Download or print',
        '',
        'Previewing Report Cards',
        'Review report cards before final download.',
        '',
        'Steps:',
        '1. Select student in Generate tab',
        '2. View the preview card',
        '3. Check all details and calculations',
        '4. Verify grades and remarks',
        '5. Make adjustments if needed',
        '',
        'Bulk Download',
        'Download report cards for an entire class at once.',
        '',
        'Steps:',
        '1. Go to Report Cards > Bulk Download',
        '2. Select examination and class',
        '3. Choose download options',
        '4. Click download all',
        '5. Files download individually',
    ];
    
    yPos = 50;
    reportCardsText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 12: Finance
    addNewPage('Chapter 12 - Finance');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 12', 15, 30);
    doc.setFontSize(20);
    doc.text('Finance', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const financeText = [
        'Fee Structure Setup',
        'Define fee categories and amounts for different grade levels.',
        '',
        'Steps:',
        '1. Go to Finance > Fee Structure',
        '2. Create fee categories (Tuition, Boarding, etc.)',
        '3. Define fee amounts per grade level',
        '4. Set term-specific fees',
        '5. Mark optional vs required fees',
        '6. Save fee structure',
        '',
        'Recording Payments',
        'Record student payments and update fee balances.',
        '',
        'Steps:',
        '1. Go to Finance > Payments',
        '2. Search for student',
        '3. Enter payment amount',
        '4. Select payment method',
        '5. Add reference number',
        '6. Record the transaction',
        '',
        'Fee Balance Management',
        'Track outstanding balances for all students.',
        '',
        'Steps:',
        '1. View student fee balances',
        '2. Filter by balance amount',
        '3. Generate balance statements',
        '4. Send reminders to defaulters',
        '5. Update balances after payments',
        '',
        'Financial Reports',
        'Generate comprehensive financial reports.',
        '',
        'Steps:',
        '1. Go to Finance > Reports',
        '2. Select report type and date range',
        '3. Generate the report',
        '4. View charts and summaries',
        '5. Export as PDF or CSV',
    ];
    
    yPos = 50;
    financeText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 13: Announcements
    addNewPage('Chapter 13 - Announcements');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 13', 15, 30);
    doc.setFontSize(20);
    doc.text('Announcements', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const announcementsText = [
        'Creating Announcements',
        'Create announcements for students, teachers, parents, or specific groups.',
        '',
        'Steps:',
        '1. Go to Announcements',
        '2. Click "New Announcement"',
        '3. Enter title and content',
        '4. Select target audience',
        '5. Add attachments if needed',
        '6. Schedule or publish immediately',
        '7. Send notification',
        '',
        'Scheduling Announcements',
        'Schedule announcements to be sent at specific times.',
        '',
        'Steps:',
        '1. Create announcement as usual',
        '2. Select "Schedule" instead of "Publish"',
        '3. Set date and time',
        '4. Confirm schedule',
        '5. Monitor scheduled announcements',
        '',
        'Managing Attachments',
        'Attach documents, images, or other files to announcements.',
        '',
        'Steps:',
        '1. Create or edit announcement',
        '2. Click "Add Attachment"',
        '3. Select file from device',
        '4. Add description if needed',
        '5. Save announcement',
    ];
    
    yPos = 50;
    announcementsText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Chapter 14: Troubleshooting
    addNewPage('Chapter 14 - Troubleshooting');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 14', 15, 30);
    doc.setFontSize(20);
    doc.text('Troubleshooting', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const troubleshootingData = [
        ['Problem', 'Solution'],
        ['Cannot log in with correct credentials', 'Clear browser cache and cookies, then try again. If the issue persists, reset your password.'],
        ['Forgot password', 'Click "Forgot password" on the login page and follow the instructions sent to your email.'],
        ['Account locked', 'Contact your system administrator to unlock your account.'],
        ['Results not showing', 'Ensure the examination has been published. Unpublished results are not visible in reports.'],
        ['Students not appearing in class', 'Check that students are assigned to the correct class and their status is "active".'],
        ['Old data appearing', 'Clear your browser cache or try a different browser. Ensure you have selected the correct academic year and term.'],
        ['Report card not generating', 'Ensure all subject marks are entered and the exam is published. Check that grade scales are configured.'],
        ['PDF download fails', 'Check your browser\'s download settings. Disable any download managers and try again.'],
        ['Incorrect calculations on report', 'Verify that maximum marks are set correctly for each subject. Check grade scale configuration.'],
        ['System is slow', 'Check your internet connection. Close other browser tabs. Try during off-peak hours.'],
        ['Page not loading', 'Refresh the page. Check that you have a stable internet connection. Try a different browser.'],
        ['Timeout errors', 'Reduce the amount of data being processed. Try exporting smaller batches of data.'],
    ];
    
    autoTable(doc, {
        startY: 45,
        head: [troubleshootingData[0]],
        body: troubleshootingData.slice(1),
        theme: 'grid',
        headStyles: {
            fillColor: primaryColor,
            textColor: 255,
            fontStyle: 'bold',
            fontSize: 9,
        },
        bodyStyles: {
            fontSize: 8,
            cellPadding: 2,
            valign: 'top',
        },
        columnStyles: {
            0: { cellWidth: 50, fontStyle: 'bold' },
            1: { cellWidth: 110 }
        },
        alternateRowStyles: {
            fillColor: [245, 255, 245],
        },
        margin: { left: 15, right: 15 },
    });

    // Chapter 15: FAQ
    addNewPage('Chapter 15 - FAQ');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 15', 15, 30);
    doc.setFontSize(20);
    doc.text('Frequently Asked Questions', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const faqData = [
        ['Question', 'Answer'],
        ['Can I edit published results?', 'Published results can be edited by administrators with appropriate permissions. Go to the exam, click "Edit Results", make changes, and republish.'],
        ['How do I regenerate report cards?', 'Go to Report Cards, select the examination and class, and generate new report cards. Previous versions are not overwritten.'],
        ['How do I reset passwords?', 'Users can reset their own passwords using "Forgot password" on the login page. Administrators can reset passwords from the user management section.'],
        ['Is my data secure?', 'Yes, NexaLMS uses industry-standard encryption and security measures. Regular backups are performed, and access is controlled by permissions.'],
        ['Can I access NexaLMS on mobile?', 'Yes, NexaLMS is responsive and works on mobile devices. However, some features are best used on a larger screen.'],
        ['What browsers are supported?', 'NexaLMS supports the latest versions of Chrome, Firefox, Safari, and Edge. Internet Explorer is not supported.'],
        ['Do I need to install software?', 'No, NexaLMS is entirely web-based. You only need a modern web browser and internet connection.'],
        ['How often is the system backed up?', 'Data is backed up daily. Additional backups are performed before major updates.'],
    ];
    
    autoTable(doc, {
        startY: 45,
        head: [faqData[0]],
        body: faqData.slice(1),
        theme: 'grid',
        headStyles: {
            fillColor: primaryColor,
            textColor: 255,
            fontStyle: 'bold',
            fontSize: 9,
        },
        bodyStyles: {
            fontSize: 8,
            cellPadding: 2,
            valign: 'top',
        },
        columnStyles: {
            0: { cellWidth: 50, fontStyle: 'bold' },
            1: { cellWidth: 110 }
        },
        alternateRowStyles: {
            fillColor: [245, 255, 245],
        },
        margin: { left: 15, right: 15 },
    });

    // Chapter 16: Support
    addNewPage('Chapter 16 - Support');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 139, 34);
    doc.text('Chapter 16', 15, 30);
    doc.setFontSize(20);
    doc.text('Support & Contact', 15, 38);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const supportText = [
        'Contact Information',
        '',
        '📞 Phone: +254 719 637 416',
        '💬 WhatsApp: +254 719 637 416',
        '📧 Email: support@nexagen.co.ke',
        '🌐 Website: www.nexagen.co.ke',
        '',
        'Response Times',
        '',
        '• Critical issues: Within 2 hours',
        '• High priority: Within 4 hours',
        '• Normal priority: Within 24 hours',
        '• Low priority: Within 48 hours',
        '',
        'When contacting support, please include:',
        '',
        '• Your school name',
        '• Your name and role',
        '• A detailed description of the issue',
        '• Steps to reproduce the problem',
        '• Screenshots if applicable',
        '',
        'Training Resources',
        '',
        '• Download this user manual',
        '• Watch video tutorials (coming soon)',
        '• Schedule on-site training',
        '• Join webinars and workshops',
        '• Access the knowledge base',
    ];
    
    yPos = 50;
    supportText.forEach(line => {
        doc.text(line, 15, yPos);
        yPos += 6;
    });

    // Update total pages
    totalPages = currentPage;
    
    // Update page numbers on all pages
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        addPageHeader(i, i === 2 ? 'Table of Contents' : undefined);
        addPageFooter();
    }

    return doc;
}

export function downloadPdf(doc: jsPDF, fileName: string) {
    const pdfBlob = doc.output('blob');
    const url = URL.createObjectURL(pdfBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileName}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
}
