import type { GeneratedEntry } from './types';
import { DAY_NAMES } from './generator';

interface PdfOptions {
    schoolName: string;
    title: string;
    subtitle: string;
    version: number;
    watermarkUrl?: string;
    entries: GeneratedEntry[];
    viewType: 'master' | 'teacher' | 'class';
    filterName?: string;
    periods: number[];
    workingDays: number[];
}

function formatDate() {
    return new Date().toLocaleString('en-KE', {
        day: '2-digit', month: 'short', year: 'numeric',
        hour: '2-digit', minute: '2-digit', hour12: true,
    });
}

function buildTableHtml(options: PdfOptions): string {
    const { entries, viewType, periods, workingDays } = options;
    const dayHeaders = workingDays.map(d => DAY_NAMES[d]?.slice(0, 3) || `D${d}`);

    let body = '';
    for (const period of periods) {
        body += '<tr><td class="period">P' + period + '</td>';
        for (const day of workingDays) {
            if (viewType === 'master') {
                const cellEntries = entries.filter(e => e.period_number === period && e.day_of_week === day);
                const cell = cellEntries.length
                    ? cellEntries.map(e => `<div class="lesson"><strong>${e.class_name}</strong><br>${e.subject_name}<br><em>${e.teacher_name}</em></div>`).join('')
                    : '—';
                body += `<td class="master-cell">${cell}</td>`;
            } else {
                const e = entries.find(x => x.period_number === period && x.day_of_week === day);
                body += `<td>${e ? `<strong>${e.subject_name}</strong><br><em>${e.teacher_name || ''}</em>` : '—'}</td>`;
            }
        }
        body += '</tr>';
    }

    return `<table>
        <thead><tr><th></th>${dayHeaders.map(h => `<th>${h}</th>`).join('')}</tr></thead>
        <tbody>${body}</tbody>
    </table>`;
}

export async function downloadTimetablePdf(options: PdfOptions): Promise<void> {
    const { schoolName, title, subtitle, version, watermarkUrl, filterName } = options;
    const tableHtml = buildTableHtml(options);

    const html = `<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>${title} - V${version}</title>
<style>
  @page { size: landscape; margin: 12mm; }
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 20px; color: #1f2937; position: relative; }
  .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%,-50%); opacity: 0.06; width: 200px; z-index: 0; }
  .content { position: relative; z-index: 1; }
  h1 { text-align: center; font-size: 18px; margin: 0 0 4px; text-transform: uppercase; letter-spacing: 1px; }
  h2 { text-align: center; font-size: 14px; margin: 0 0 4px; color: #059669; text-transform: uppercase; }
  .filter { text-align: center; font-size: 13px; font-weight: 600; margin-bottom: 4px; }
  .subtitle { text-align: center; font-size: 11px; color: #6b7280; margin-bottom: 16px; text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; font-size: 10px; }
  th { background: #059669; color: white; padding: 8px 4px; border: 1px solid #047857; }
  td { border: 1px solid #d1d5db; padding: 6px 4px; text-align: center; vertical-align: middle; min-height: 40px; }
  td.period { background: #f3f4f6; font-weight: 700; width: 50px; }
  td.master-cell { text-align: left; vertical-align: top; font-size: 8px; }
  .lesson { margin-bottom: 4px; padding-bottom: 4px; border-bottom: 1px dashed #e5e7eb; }
  .lesson:last-child { border-bottom: none; }
  .footer { text-align: center; margin-top: 16px; font-size: 9px; color: #9ca3af; }
</style>
</head><body>
${watermarkUrl ? `<img class="watermark" src="${watermarkUrl}" alt="" />` : ''}
<div class="content">
  <h1>${schoolName}</h1>
  <h2>${title}</h2>
  ${filterName ? `<div class="filter">${filterName}</div>` : ''}
  <div class="subtitle">${subtitle}</div>
  ${tableHtml}
  <div class="footer">Generated by NexaLMS &nbsp;|&nbsp; ${formatDate()} &nbsp;|&nbsp; Version V${version}</div>
</div>
<script>window.onload = () => { window.print(); }</script>
</body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, '_blank');
    if (!win) {
        URL.revokeObjectURL(url);
        throw new Error('Pop-up blocked. Allow pop-ups to download the timetable PDF.');
    }
    setTimeout(() => URL.revokeObjectURL(url), 60000);
}

export function getEntriesForTeacher(entries: GeneratedEntry[], teacherId: string) {
    return entries.filter(e => e.teacher_id === teacherId);
}

export function getEntriesForClass(entries: GeneratedEntry[], classId: string) {
    return entries.filter(e => e.class_id === classId);
}
